spring.application.name=EcommerceWebsite
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/fsdintern
spring.datasource.username=root
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=udhaya33
